kernel/generic: fix build failure on missing uhci symbol
linux-3.6.8/drivers/usb/host/pci-quirks.c:471: undefined reference to
`uhci_check_and_reset_hc'

Signed-off-by: Florian Fainelli <florian@openwrt.org>

SVN-Revision: 34599