Revert "dnsmasq: follow upstream dnsmasq pre-v2.81"
This reverts commit adeebbf6160afe8669718d101265e8b53ded75a2.

buildbot found an error
option.c: In function 'dhcp_context_free':
option.c:1042:15: error: 'struct dhcp_context' has no member named 'template_interface'
       free(ctx->template_interface);

revert for the moment

Signed-off-by: Kevin Darbyshire-Bryant <ldir@darbyshire-bryant.me.uk>